project:
  name: FGAD API
  resource: null
  uriDocumentResource: http://localhost:8080/ged-dfc-api/fgad/api/clients/synchrone
  connectionTimeOut: 10000

logging:
  level:
    org.springframework.web: DEBUG
    com.socgen: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
  file: /fgad-api.log